List<Map<String, dynamic>> Constituency = [
  { "ccode": "10001", "cname": "Nippani", "state": "Karnataka" },
  { "ccode": "10002", "cname": "Chikkodi-Sadalga", "state": "Karnataka" },
  { "ccode": "10003", "cname": "Athani", "state": "Karnataka" },
  { "ccode": "10004", "cname": "Kagwad", "state": "Karnataka" },
  { "ccode": "10005", "cname": "Kudachi(SC)", "state": "Karnataka" },
  { "ccode": "10006", "cname": "Raybag(SC)", "state": "Karnataka" },
  { "ccode": "10007", "cname": "Hukkeri", "state": "Karnataka" },
  { "ccode": "10008", "cname": "Arabhavi", "state": "Karnataka" },
  { "ccode": "10009", "cname": "Gokak", "state": "Karnataka" },
  { "ccode": "10010", "cname": "Yemkanmardi(ST)", "state": "Karnataka" },
  { "ccode": "10011", "cname": "Belgaum Uttar", "state": "Karnataka" },
  { "ccode": "10012", "cname": "Belgaum Dakshin", "state": "Karnataka" },
  { "ccode": "10013", "cname": "Belgaum Rural", "state": "Karnataka" },
  { "ccode": "10014", "cname": "Khanapur", "state": "Karnataka" },
  { "ccode": "10015", "cname": "Kittur", "state": "Karnataka" },
  { "ccode": "10016", "cname": "Bailhongal", "state": "Karnataka" },
  { "ccode": "10017", "cname": "Saundatti Yellamma", "state": "Karnataka" },
  { "ccode": "10018", "cname": "Ramdurg", "state": "Karnataka" },
  { "ccode": "10019", "cname": "Mudhol(SC)", "state": "Karnataka" },
  { "ccode": "10020", "cname": "Terdal", "state": "Karnataka" },
  { "ccode": "10021", "cname": "Jamkhandi", "state": "Karnataka" },
  { "ccode": "10022", "cname": "Bilgi", "state": "Karnataka" },
  { "ccode": "10023", "cname": "Badami", "state": "Karnataka" },
  { "ccode": "10024", "cname": "Bagalkot", "state": "Karnataka" },
  { "ccode": "10025", "cname": "Hungund", "state": "Karnataka" },
  { "ccode": "10026", "cname": "Muddebihal", "state": "Karnataka" },
  { "ccode": "10027", "cname": "Devar Hippargi", "state": "Karnataka" },
  { "ccode": "10028", "cname": "Basavana Bagevadi", "state": "Karnataka" },
  { "ccode": "10029", "cname": "Babaleshwar", "state": "Karnataka" },
  { "ccode": "10030", "cname": "Bijapur City", "state": "Karnataka" },
  { "ccode": "10031", "cname": "Nagthan(SC)", "state": "Karnataka" },
  { "ccode": "10032", "cname": "Indi", "state": "Karnataka" },
  { "ccode": "10033", "cname": "Sindgi", "state": "Karnataka" },
  { "ccode": "10034", "cname": "Afzalpur", "state": "Karnataka" },
  { "ccode": "10035", "cname": "Jewargi", "state": "Karnataka" },
  { "ccode": "10036", "cname": "Shorapur(ST)", "state": "Karnataka" },
  { "ccode": "10037", "cname": "Shahapur", "state": "Karnataka" },
  { "ccode": "10038", "cname": "Yadgri", "state": "Karnataka" },
  { "ccode": "10039", "cname": "Gurmitkal", "state": "Karnataka" },
  { "ccode": "10040", "cname": "Chittapur (SC)", "state": "Karnataka" },
  { "ccode": "10041", "cname": "Sedam", "state": "Karnataka" },
  { "ccode": "10042", "cname": "Chincholi (SC)", "state": "Karnataka" },
  { "ccode": "10043", "cname": "Gulbarga Rural(SC)", "state": "Karnataka" },
  { "ccode": "10044", "cname": "Gulbarga Dakshin", "state": "Karnataka" },
  { "ccode": "10045", "cname": "Gulbarga Uttar", "state": "Karnataka" },
  { "ccode": "10046", "cname": "Aland", "state": "Karnataka" },
  { "ccode": "10047", "cname": "Basavakalyan", "state": "Karnataka" },
  { "ccode": "10048", "cname": "Humnabad", "state": "Karnataka" },
  { "ccode": "10049", "cname": "BidarSouth ", "state": "Karnataka" },
  { "ccode": "10050", "cname": "Bidar", "state": "Karnataka" },
  { "ccode": "10051", "cname": "Bhalki", "state": "Karnataka" },
  { "ccode": "10052", "cname": "Aurad (SC)", "state": "Karnataka" },
  { "ccode": "10053", "cname": "Raichur Rural(ST)", "state": "Karnataka" },
  { "ccode": "10054", "cname": "Raichur", "state": "Karnataka" },
  { "ccode": "10055", "cname": "Manvi(ST)", "state": "Karnataka" },
  { "ccode": "10056", "cname": "Devadurga (ST)", "state": "Karnataka" },
  { "ccode": "10057", "cname": "Lingsugur (SC)", "state": "Karnataka" },
  { "ccode": "10058", "cname": "Sindhanur", "state": "Karnataka" },
  { "ccode": "10059", "cname": "Maski (ST)", "state": "Karnataka" },
  { "ccode": "10060", "cname": "Kushatgi", "state": "Karnataka" },
  { "ccode": "10061", "cname": "kanakagiri(SC)", "state": "Karnataka" },
  { "ccode": "10062", "cname": "Gangawati", "state": "Karnataka" },
  { "ccode": "10063", "cname": "Yelburga", "state": "Karnataka" },
  { "ccode": "10064", "cname": "Koppal", "state": "Karnataka" },
  { "ccode": "10065", "cname": "Shirahatti(SC)", "state": "Karnataka" },
  { "ccode": "10066", "cname": "Gadag", "state": "Karnataka" },
  { "ccode": "10067", "cname": "Ron", "state": "Karnataka" },
  { "ccode": "10068", "cname": "Nargund", "state": "Karnataka" },
  { "ccode": "10069", "cname": "Navalgund", "state": "Karnataka" },
  { "ccode": "10070", "cname": "Kundgol", "state": "Karnataka" },
  { "ccode": "10071", "cname": "Dharwad", "state": "Karnataka" },
  { "ccode": "10072", "cname": "Hubli-Dharwad-East (SC)", "state": "Karnataka" },
  { "ccode": "10073", "cname": "Hubli-Dharwad Central", "state": "Karnataka" },
  { "ccode": "10074", "cname": "Hubli-Dharwad-West", "state": "Karnataka" },
  { "ccode": "10075", "cname": "Kalghatgi", "state": "Karnataka" },
  { "ccode": "10076", "cname": "Haliyal", "state": "Karnataka" },
  { "ccode": "10077", "cname": "Karwar", "state": "Karnataka" },
  { "ccode": "10078", "cname": "Kumta", "state": "Karnataka" },
  { "ccode": "10079", "cname": "Bhatkal", "state": "Karnataka" },
  { "ccode": "10080", "cname": "Sirsi", "state": "Karnataka" },
  { "ccode": "10081", "cname": "Yellapur", "state": "Karnataka" },
  { "ccode": "10082", "cname": "Hangal", "state": "Karnataka" },
  { "ccode": "10083", "cname": "Shiggaon", "state": "Karnataka" },
  { "ccode": "10084", "cname": "Haveri (SC)", "state": "Karnataka" },
  { "ccode": "10085", "cname": "Byadgi", "state": "Karnataka" },
  { "ccode": "10086", "cname": "Hirekerur", "state": "Karnataka" },
  { "ccode": "10087", "cname": "Ranebennur", "state": "Karnataka" },
  { "ccode": "10088", "cname": "Hadagalli (SC)", "state": "Karnataka" },
  { "ccode": "10089", "cname": "Hagaribommanahalli (SC)", "state": "Karnataka" },
  { "ccode": "10090", "cname": "Vijayanagara", "state": "Karnataka" },
  { "ccode": "10091", "cname": "Kampli (ST)", "state": "Karnataka" },
  { "ccode": "10092", "cname": "Siruguppa (ST)", "state": "Karnataka" },
  { "ccode": "10093", "cname": "Bellary (ST)", "state": "Karnataka" },
  { "ccode": "10094", "cname": "Bellary City", "state": "Karnataka" },
  { "ccode": "10095", "cname": " Sandur (ST)", "state": "Karnataka" },
  { "ccode": "10096", "cname": "Kidligi (ST)", "state": "Karnataka" },
  { "ccode": "10097", "cname": " Molakalmuru (ST)", "state": "Karnataka" },
  { "ccode": "10098", "cname": "Challakere (ST)", "state": "Karnataka" },
  { "ccode": "10099", "cname": "Chitradurga (ST)", "state": "Karnataka" },
  { "ccode": "10100", "cname": "Hiriyur", "state": "Karnataka" },
  { "ccode": "10101", "cname": "Hosadurga", "state": "Karnataka" },
  { "ccode": "10102", "cname": "Holalkere (SC)", "state": "Karnataka" },
  { "ccode": "10103", "cname": "Jagalur (ST)", "state": "Karnataka" },
  { "ccode": "10104", "cname": "Harapanahalli", "state": "Karnataka" },
  { "ccode": "10105", "cname": "Harihar", "state": "Karnataka" },
  { "ccode": "10106", "cname": "Devanagere North", "state": "Karnataka" },
  { "ccode": "10107", "cname": "Devanagere South", "state": "Karnataka" },
  { "ccode": "10108", "cname": "Mayakonda (SC)", "state": "Karnataka" },
  { "ccode": "10109", "cname": "Channagiri", "state": "Karnataka" },
  { "ccode": "10110", "cname": "Honnali", "state": "Karnataka" },
  { "ccode": "10111", "cname": "Shimoga Rural (SC)", "state": "Karnataka" },
  { "ccode": "10112", "cname": "Bhadarvati", "state": "Karnataka" },
  { "ccode": "10113", "cname": "Shimoga", "state": "Karnataka" },
  { "ccode": "10114", "cname": "Tirthahalli", "state": "Karnataka" },
  { "ccode": "10115", "cname": "Shikaripura", "state": "Karnataka" },
  { "ccode": "10116", "cname": "Sorab", "state": "Karnataka" },
  { "ccode": "10117", "cname": "Sagar", "state": "Karnataka" },
  { "ccode": "10118", "cname": "Byndoor", "state": "Karnataka" },
  { "ccode": "10119", "cname": "Kundapura", "state": "Karnataka" },
  { "ccode": "10120", "cname": "Ufdupi", "state": "Karnataka" },
  { "ccode": "10121", "cname": "Kaup", "state": "Karnataka" },
  { "ccode": "10122", "cname": "Karkala", "state": "Karnataka" },
  { "ccode": "10123", "cname": "Sringeri", "state": "Karnataka" },
  { "ccode": "10124", "cname": "Mudigere (SC)", "state": "Karnataka" },
  { "ccode": "10125", "cname": "chikmagalur", "state": "Karnataka" },
  { "ccode": "10126", "cname": "Tarikere", "state": "Karnataka" },
  { "ccode": "10127", "cname": "Kadur", "state": "Karnataka" },
  { "ccode": "10128", "cname": "Chikknaykanhalli", "state": "Karnataka" },
  { "ccode": "10129", "cname": "Tiptur", "state": "Karnataka" },
  { "ccode": "10130", "cname": "Turuvekere", "state": "Karnataka" },
  { "ccode": "10131", "cname": "Kunigal", "state": "Karnataka" },
  { "ccode": "10132", "cname": "Tumkur City", "state": "Karnataka" },
  { "ccode": "10133", "cname": "Tumkur Rural", "state": "Karnataka" },
  { "ccode": "10134", "cname": "Koratagere (SC)", "state": "Karnataka" },
  { "ccode": "10135", "cname": "Gubbi", "state": "Karnataka" },
  { "ccode": "10136", "cname": "Sira", "state": "Karnataka" },
  { "ccode": "10137", "cname": "Pavagada (SC)", "state": "Karnataka" },
  { "ccode": "10138", "cname": "Madhugiri", "state": "Karnataka" },
  { "ccode": "10139", "cname": "Gauribidanur", "state": "Karnataka" },
  { "ccode": "10140", "cname": "Bagepalli", "state": "Karnataka" },
  { "ccode": "10141", "cname": "Chikkaballapur", "state": "Karnataka" },
  { "ccode": "10142", "cname": "Sidlaghatta", "state": "Karnataka" },
  { "ccode": "10143", "cname": "Chintamani", "state": "Karnataka" },
  { "ccode": "10144", "cname": "Srinivaspur", "state": "Karnataka" },
  { "ccode": "10145", "cname": "Mulbagal (SC)", "state": "Karnataka" },
  { "ccode": "10146", "cname": "Kolar Gold field (SC)", "state": "Karnataka" },
  { "ccode": "10147", "cname": "Bangarapet (SC)", "state": "Karnataka" },
  { "ccode": "10148", "cname": "Kolar", "state": "Karnataka" },
  { "ccode": "10149", "cname": "Malur", "state": "Karnataka" },
  { "ccode": "10150", "cname": "Yelahanka", "state": "Karnataka" },
  { "ccode": "10151", "cname": "K.R Pura", "state": "Karnataka" },
  { "ccode": "10152", "cname": "Byatarayanapura", "state": "Karnataka" },
  { "ccode": "10153", "cname": "Yeshvanthapura", "state": "Karnataka" },
  { "ccode": "10154", "cname": "Rajarajeshwarinagar", "state": "Karnataka" },
  { "ccode": "10155", "cname": "Dasarahalli", "state": "Karnataka" },
  { "ccode": "10156", "cname": "Mahalaksshmi Layout", "state": "Karnataka" },
  { "ccode": "10157", "cname": "Malleshwaram", "state": "Karnataka" },
  { "ccode": "10158", "cname": "Hebbi", "state": "Karnataka" },
  { "ccode": "10159", "cname": "Pulakeshinagar (SC)", "state": "Karnataka" },
  { "ccode": "10160", "cname": "Sarvagnanagar", "state": "Karnataka" },
  { "ccode": "10161", "cname": "C.V Raman Nagar (SC)", "state": "Karnataka" },
  { "ccode": "10162", "cname": "Shivajinagar", "state": "Karnataka" },
  { "ccode": "10163", "cname": "Shanti Nagar", "state": "Karnataka" },
  { "ccode": "10164", "cname": "Gandhi Nagar", "state": "Karnataka" },
  { "ccode": "10165", "cname": "Rajaji Nagar", "state": "Karnataka" },
  { "ccode": "10166", "cname": "Govindraj Nagr", "state": "Karnataka" },
  { "ccode": "10167", "cname": "Vijay Nagar", "state": "Karnataka" },
  { "ccode": "10168", "cname": "Chamrajpet", "state": "Karnataka" },
  { "ccode": "10169", "cname": "Chickpet", "state": "Karnataka" },
  { "ccode": "10170", "cname": "Basavanagudi", "state": "Karnataka" },
  { "ccode": "10171", "cname": "Padmanaba Nagar", "state": "Karnataka" },
  { "ccode": "10172", "cname": "B.T.M Layout", "state": "Karnataka" },
  { "ccode": "10173", "cname": "Jayanagar", "state": "Karnataka" },
  { "ccode": "10174", "cname": "Mahadevapura", "state": "Karnataka" },
  { "ccode": "10175", "cname": "Bommanahalli", "state": "Karnataka" },
  { "ccode": "10176", "cname": "Bangalore South", "state": "Karnataka" },
  { "ccode": "10177", "cname": "Anekal (SC)", "state": "Karnataka" },
  { "ccode": "10178", "cname": "Hosakote", "state": "Karnataka" },
  { "ccode": "10179", "cname": "Devanahalli (SC)", "state": "Karnataka" },
  { "ccode": "10180", "cname": "Dobbaballapur", "state": "Karnataka" },
  { "ccode": "10181", "cname": "Nelamangala (SC)", "state": "Karnataka" },
  { "ccode": "10182", "cname": "Magadi", "state": "Karnataka" },
  { "ccode": "10183", "cname": "Ramanagaram", "state": "Karnataka" },
  { "ccode": "10184", "cname": "KanaKapura", "state": "Karnataka" },
  { "ccode": "10185", "cname": "Channapatna", "state": "Karnataka" },
  { "ccode": "10186", "cname": "Malavalli (SC)", "state": "Karnataka" },
  { "ccode": "10187", "cname": "Maddur", "state": "Karnataka" },
  { "ccode": "10188", "cname": "Melukote", "state": "Karnataka" },
  { "ccode": "10189", "cname": "Mandya", "state": "Karnataka" },
  { "ccode": "10190", "cname": "Shrirangapattana", "state": "Karnataka" },
  { "ccode": "10191", "cname": "Nagamangala", "state": "Karnataka" },
  { "ccode": "10192", "cname": "Krishnarajapet", "state": "Karnataka" },
  { "ccode": "10193", "cname": "Shravanabelagola", "state": "Karnataka" },
  { "ccode": "10194", "cname": "Arsikere", "state": "Karnataka" },
  { "ccode": "10195", "cname": "Belur", "state": "Karnataka" },
  { "ccode": "10196", "cname": "Hassan", "state": "Karnataka" },
  { "ccode": "10197", "cname": "Holenarsasipur", "state": "Karnataka" },
  { "ccode": "10198", "cname": "Arkalgud", "state": "Karnataka" },
  { "ccode": "10199", "cname": "Sakaleshpur (SC)", "state": "Karnataka" },
  { "ccode": "10200", "cname": "Belthangady", "state": "Karnataka" },
  { "ccode": "10201", "cname": "Moodabidri", "state": "Karnataka" },
  { "ccode": "10202", "cname": "Mangalore City North", "state": "Karnataka" },
  { "ccode": "10203", "cname": "Mangalore City South ", "state": "Karnataka" },
  { "ccode": "10204", "cname": "Mangalore", "state": "Karnataka" },
  { "ccode": "10205", "cname": "Bantwal", "state": "Karnataka" },
  { "ccode": "10206", "cname": "Puttur", "state": "Karnataka" },
  { "ccode": "10207", "cname": "Sullia (SC)", "state": "Karnataka" },
  { "ccode": "10208", "cname": "MadiKeri", "state": "Karnataka" },
  { "ccode": "10209", "cname": "Virajpet", "state": "Karnataka" },
  { "ccode": "10210", "cname": "Piriyapatna", "state": "Karnataka" },
  { "ccode": "10211", "cname": "Krishnarajanagara", "state": "Karnataka" },
  { "ccode": "10212", "cname": "Hunsur", "state": "Karnataka" },
  { "ccode": "10213", "cname": "Heggadadevankote (ST)", "state": "Karnataka" },
  { "ccode": "10214", "cname": "Nanjangud (ST)", "state": "Karnataka" },
  { "ccode": "10215", "cname": "Chamundeshwari", "state": "Karnataka" },
  { "ccode": "10216", "cname": "Krishnaraj", "state": "Karnataka" },
  { "ccode": "10217", "cname": "Chamaraja", "state": "Karnataka" },
  { "ccode": "10218", "cname": "Narasimharaja", "state": "Karnataka" },
  { "ccode": "10219", "cname": "Varuna", "state": "Karnataka" },
  { "ccode": "10220", "cname": "T.NArasipur", "state": "Karnataka" },
  { "ccode": "10221", "cname": "Hanur", "state": "Karnataka" },
  { "ccode": "10222", "cname": "Kollegal (SC)", "state": "Karnataka" },
  { "ccode": "10223", "cname": " Chamarajanagar", "state": "Karnataka" },
  { "ccode": "10224", "cname": "Gundlupet", "state": "Karnataka" },
];

